import { writeFile } from 'node:fs/promises';
export const projects = [
['OpenMausBot V2','OpenMausBotV2','AI systems','A team of AI bots in one chat workspace, with individual models, computers, and app connections.','Claude · Codex · NVIDIA NIM','agents'],
['Auric Terminal','auric-terminal','Applications','A gold trading research terminal with strategy backtesting, risk controls, a trade journal, and a React interface. Engineering MVP.','React · TypeScript · FastAPI','terminal'],
['ClipForge V2','ClipForge-V2','Applications','A local-first video studio for clipping, voiceovers, transcription, and export management on Windows and the web.','Python · FFmpeg · NVIDIA NIM','video'],
['Munim Ledger','munim-ledger','Applications','An offline-first khata for micro-merchants. No login, no ads, and device-local data in English, Hindi, and Punjabi.','PWA · Offline-first · Local storage','ledger'],
['MCPGuardLab','mcpguardlab','Security & tools','A security validation harness for Model Context Protocol integrations, built around verifiable behavior.','MCP · Security · Validation','shield'],
['CricketAAA','CricketAAA','Games & graphics','A cricket project spanning a Three.js web experience, Unreal Engine C++, and native implementations.','Three.js · Unreal Engine · C++','game'],
['HireMatch AI','hirematch-ai','AI systems','AI-assisted job matching with fit scoring, application tracking, and a zero-configuration demo.','Next.js · SQLite · NVIDIA NIM','match'],
['Nexus AI','NEXUS-AI-The-Next-Generation-AI-Agent-Operating-System','AI systems','An AI workspace exploring how people and autonomous agents can collaborate across tools and tasks.','AI agents · Web · Cloud','nexus'],
['CodeSec','codesec','Security & tools','AI-assisted security code review combining syntax analysis, scanning, taint tracking, and semantic review for pull requests.','Tree-sitter · Semgrep · LLMs','code'],
['FlakeTrack','flaketrack','Security & tools','A zero-dependency CLI that turns test runs into flake statistics, failure clusters, and actionable CI gates.','Jest · Vitest · Playwright','flake'],
['RedactScan','redactscan','Security & tools','An offline disclosure auditor to inspect what files reveal before they are shared.','Privacy · Offline · Auditing','scan'],
['Punjab Stories','punjab-stories','Games & graphics','A top-down open-world game set in a procedural Punjab city, built with vanilla JavaScript and Canvas.','JavaScript · Canvas · Procedural worlds','city'],
['PhysLab','physlab','Systems labs','A from-scratch 2D rigid-body physics engine with a conservation-law verification harness.','Physics · Integrators · Verification','physics'],
['ANNLab','annlab','Systems labs','An HNSW approximate nearest-neighbor index with recall, filtering, and deletion verification.','Search · HNSW · Algorithms','search'],
['MergeLab','mergelab','Systems labs','A from-scratch three-way merge engine with a seeded property verification harness.','Version control · Algorithms','merge'],
['FHELab','fhelab','Systems labs','A toy BFV-style homomorphic encryption lab for addition and multiplication on encrypted data.','Cryptography · Zero dependencies','crypto']
];
const categories = ['All work', ...new Set(projects.map(p=>p[2]))];
const cards = projects.map(([name,repo,category,description,stack,art],i)=>`<article class="project reveal" data-category="${category}">
<a class="project-art art-${art}" href="https://github.com/harmanhanjra/${repo}" target="_blank" rel="noopener noreferrer" aria-label="Explore ${name} on GitHub"><span class="art-index">${String(i+1).padStart(2,'0')} / ${category.toUpperCase()}</span><div class="artifact" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><b>${['◎','⌁','▷','≡','⌘','◉'][i%6]}</b></div><span class="art-name">${name}</span><span class="art-arrow" aria-hidden="true">↗</span></a>
<div class="project-copy"><span class="eyebrow">${category}</span><h3><a href="https://github.com/harmanhanjra/${repo}" target="_blank" rel="noopener noreferrer">${name} <span aria-hidden="true">↗</span></a></h3><p>${description}</p><span class="stack-label">${stack}</span></div></article>`).join('\n');
await writeFile('index.html', `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#10120f"><title>Harmanpreet Singh — AI, software & experiments</title><meta name="description" content="Harmanpreet Singh's selected projects: AI agent systems, creative tools, security engineering, games, and systems research."><meta property="og:title" content="Harmanpreet Singh — Selected work"><meta property="og:description" content="Explore AI systems, applications, security tools, and interactive worlds."><meta property="og:type" content="website"><link rel="canonical" href="https://harmanhanjra.github.io/portfolio/"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23d5fa71'/%3E%3Ctext x='12' y='46' font-size='40' font-family='Arial' fill='%2310120f'%3EH%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="styles.css"><script src="script.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><div class="reading-progress" aria-hidden="true"></div>
<header class="navigation"><a class="wordmark" href="#home" aria-label="Harman home">harman<span>®</span></a><nav aria-label="Main navigation"><a href="#projects">Selected work</a><a href="#about">About</a><a href="#contact">Contact <span aria-hidden="true">↗</span></a></nav><button id="motion-toggle" aria-pressed="false">Pause motion</button></header>
<main id="main"><section class="hero" id="home"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> HARMANPREET SINGH / SOFTWARE & AI ENGINEER</p><h1>Ideas into<br>systems.<br><em>Code into</em><br><em>possibility.</em></h1><p class="hero-description">I build AI systems, useful software, and interactive worlds. A collection of things made with curiosity—and a lot of code.</p><a class="button" href="#projects">Explore my work <span aria-hidden="true">↘</span></a></div><div class="hero-visual"><div class="orb-fallback" aria-hidden="true"></div><canvas id="scene" aria-hidden="true"></canvas><div class="scene-coordinate top">FIG. 01 — CONNECTED POSSIBILITIES</div><div class="scene-coordinate bottom"><span>AI / ENGINEERING / EXPERIMENTATION</span><span id="scene-hint">INTERACTIVE 3D SCULPTURE</span></div></div><div class="hero-footer"><span>INDEPENDENT THINKING. CONNECTED SYSTEMS.</span><a href="#projects">SCROLL TO DISCOVER ↓</a></div></section>
<div class="discipline-strip" aria-label="Areas of work"><span>AI SYSTEMS</span><b>✳</b><span>CREATIVE DEVELOPMENT</span><b>✳</b><span>SECURITY ENGINEERING</span><b>✳</b><span>INTERACTIVE WORLDS</span></div>
<section class="work section" id="projects"><div class="section-heading"><div><p class="eyebrow">01 / THE PROJECT INDEX</p><h2>Built to be<br><em>explored.</em></h2></div><p>From agent workspaces to offline tools.<br>Selected public projects, with the code behind them.<br><span class="update-date">Updated September 5, 2026</span></p></div><div class="filter-bar"><div class="filters" role="group" aria-label="Filter projects">${categories.map((c,i)=>`<button data-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}</div><span id="project-count" role="status">${projects.length} projects</span></div><div class="project-grid">${cards}</div><div class="archive-link"><span>Still curious? There’s more in the archive.</span><a href="https://github.com/harmanhanjra?tab=repositories" target="_blank" rel="noopener noreferrer">All GitHub repositories ↗</a></div></section>
<section class="about section" id="about"><p class="eyebrow">02 / THE PERSON BEHIND THE CODE</p><div class="about-layout"><h2>Curiosity is<br>the <em>constant.</em></h2><div><p class="about-lead">I'm Harmanpreet Singh, also known as Harman Hanjra. I connect full-stack engineering, AI, and security to turn complex ideas into working software.</p><p>My work moves between practical products and foundational experiments: agent orchestration, local creative tools, developer security, simulation, and algorithms built from scratch.</p><div class="capabilities"><div><span>01</span><h3>Intelligent systems</h3><p>LLM integrations, agent workflows, Python</p></div><div><span>02</span><h3>Product engineering</h3><p>React, Next.js, TypeScript, APIs</p></div><div><span>03</span><h3>Security & foundations</h3><p>Validation, privacy, systems research</p></div></div></div></div></section>
<section class="contact section" id="contact"><p class="eyebrow">03 / WHAT'S NEXT?</p><h2>Have something<br>in <em>mind?</em><span aria-hidden="true">↗</span></h2><div class="contact-bottom"><p>Let’s talk about your next product,<br>an interesting problem, or a new opportunity.</p><a class="button" href="mailto:2000sharmanpreet@gmail.com">Get in touch ↗</a></div><div class="social-links"><a href="mailto:2000sharmanpreet@gmail.com">Email ↗</a><a href="https://github.com/harmanhanjra" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://linkedin.com/in/harman-hanjra-93b3451a6" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div></section></main><footer><a class="wordmark" href="#home">harman<span>®</span></a><span>© 2026 Harmanpreet Singh</span><a href="#home">Back to top ↑</a></footer></body></html>`);
